sudo: false
dist: trusty
language: python
notifications:
  email: false
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
install: 
  - pip install -r requirements.txt
script: make test-all